/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class TriangleNumberCalculatorTest {

    @Test
    public void testValue() {
        TriangleNumberCalculator calculator = new TriangleNumberCalculator();

        
        assertEquals(1, calculator.value(1), "1st triangular number should be 1");
        assertEquals(3, calculator.value(2), "2nd triangular number should be 3");
        assertEquals(6, calculator.value(3), "3rd triangular number should be 6");
        assertEquals(10, calculator.value(4), "4th triangular number should be 10");
        assertEquals(15, calculator.value(5), "5th triangular number should be 15");

        assertThrows(IllegalArgumentException.class, () -> calculator.value(0), "n must be a positive integer");
        assertThrows(IllegalArgumentException.class, () -> calculator.value(-5), "n must be a positive integer");
    }

    @Test
    public void testAdd() {
        TriangleNumberCalculator calculator = new TriangleNumberCalculator();

   
        assertEquals(4, calculator.add(1, 2), "Sum of 1st and 2nd triangular numbers should be 4");
        assertEquals(9, calculator.add(2, 3), "Sum of 2nd and 3rd triangular numbers should be 9");
        assertEquals(13, calculator.add(4, 2), "Sum of 4th and 2nd triangular numbers should be 13");

    
        assertThrows(IllegalArgumentException.class, () -> calculator.add(0, 2), "n must be a positive integer");
        assertThrows(IllegalArgumentException.class, () -> calculator.add(3, -1), "m must be a positive integer");
    }
}